### ISSUE TITLE
Looting scrap piles crashes the game

### ISSUE THREAD

**Issue by SeanMXD** [hookmetamethod/typh.fun#1]
Every time I loot a scrap pile with ESP enabled, my game crashes.

I'm using JJSploit on a Windows 10 laptop.

Here's my log output for the last crash:

[Code = 0xC0000005]
[ExceptSymbol = NoSym]
[Eip = 0x77317A4E]
[Eax = 0x0000000D]
[Ebx = 0x1EC20348]
[Ecx = 0xBEE53260]
[Edx = 0x3EDCE3B0]
[Esi = 0x454C7140]
[Edi = 0xC1781160]
[Ebp = 0x0888F89C]
[Esp = 0x0888F894]
[Dll Base = 0x00000000]

[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x017016CF]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x01760DBD]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x017398DA]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x016E78FE]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x016E70E2]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x016E8BCA]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00801733]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x007FCD70]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x007FC64F]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x008BC0A3]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x008BB46F]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x008BACF6]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0064C9F1]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0065276F]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x006521E1]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0063BA13]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x005B921E]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00C39935]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00C610BB]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00C5E59F]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00C52ECC]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x00C4FAED]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0167DB95]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x015C167F]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x015C1C4D]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x016A88CB]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0093E9CE]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x012120D0]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x01211BDC]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0120CC9D]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x0120CD8A]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: RobloxPlayerBeta.exe]  [RebaseAddr: 0x01FA4D90]  [BaseAddr: 0x00870000]
[File: UnkFile] [Module: KERNEL32.DLL]          [RebaseAddr: 0x0041FA29]  [BaseAddr: 0x76370000]
[File: UnkFile] [Module: ntdll.dll]             [RebaseAddr: 0x00467A7E]  [BaseAddr: 0x772B0000]
[File: UnkFile] [Module: ntdll.dll]             [RebaseAddr: 0x00467A4E]  [BaseAddr: 0x772B0000]

**Comment by hookmetamethod** [comment]
As the repository name says, this is an "archive" really can't do much about it,
On side notes, the most probable thing here happening is that WeAreDevs API (JJSploit DLL) doesn't handle properly the Drawing Library and instead crashes I recommend you using another executor such as [Krnl](https://krnl.ca/) or [Synapse X](https://x.synapse.to/)
